version: "3"
services:
  nginx:
    ports: 
      - "3300:80"
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_DB_NAME=sale_records
      - MYSQL_HOST=db
    command: npm run dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

